apiVersion: v2
name: nginx
description: Nginx workload (umbrella chart for GitOps learning)
type: application
version: 0.1.0

dependencies:
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 15.*.*
